commerce_avatax.settings:
  type: config_object
  label: 'Avalara Avatax settings'
  mapping:
    api_mode:
      type: string
      label: 'API mode'
    api_key:
      type: string
      label: 'API key'
    api_uid:
      type: string
      label: 'API UID'
    license_key:
      type: string
      label: 'License'
    company_code:
      type: string
      label: 'Company code'
    tax_code:
      type: string
      label: 'The default tax code'
